spring:
  cloud:
    aws:
      secretsmanager:
        region: ap-northeast-2
---
spring.config.activate.on-profile: local
test:
  id: jean
  password: local
---
spring.config.activate.on-profile: dev
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dokotlin?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: info
    com.yolo.jean: info
    org.hibernate.type: info
test:
  id: jean
  password: localtest
---
spring.config.activate.on-profile: sandbox
test:
  id: jean
  password: sandbox
---
spring.config.activate.on-profile: beta
test:
  id: jean
  password: beta
---
spring:
  config:
    activate:
      on-profile: production
    import: optional:aws-secretsmanager:prod/happyending/db
  cloud:
    aws:
      secretsmanager:
        enabled: true
