spring:
  config:
    activate:
      on-profile: local
  cloud:
    stream:
      kafka:
        binder:
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          consumer-properties:
            auto.offset.reset: latest
        bindings:
          topicConsumer-in-0:
            consumer:
              dlq-name: topicConsumerFail
              enable-dlq: true
      bindings:
        topicConsumer-in-0:
          destination: stream-topic
          consumer:
            max-attempts: 3
            batch-mode: false
          group: happyEndingGroup
          binder: inner-kafka
        chargeConsumer-in-0:
          error-handler-definition: myErrorHandler
          destination: acc.charge.event.v1
          consumer:
            max-attempts: 1
            batch-mode: false
          group: happyEndingGroup
          binder: inner-kafka
      binders:
        inner-kafka:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: localhost:9092,localhost:9093,localhost:9094
      default-binder: inner-kafka

logging:
  level:
    org.springframework.web: DEBUG
    com.kakaopaysec.happyending: DEBUG
