spring:
  application:
    name: happy-ending-consumer
  cloud:
    function:
      definition: topicConsumer;chargeConsumer;
    stream:
      kafka:
        bindings:
          topicConsumer-in-0:
            consumer:
              start-offset: earliest
              configuration:
                key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: "*"
                spring.json.value.default.type: com.kakaopaysec.happyending.consumer.listener.Person
          chargeConsumer-in-0:
            consumer:
              start-offset: earliest
              configuration:
                key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                spring.deserializer.value.delegate.class: com.kakaopaysec.happyending.consumer.config.CustomJsonDeserializer
                spring.json.trusted.packages: "*"
                spring.json.value.default.type: com.kakaopaysec.happyending.consumer.model.ChargeEvent
      binders:
        inner-kafka:
          type: kafka

