spring:
  application:
    name: happy-ending-consumer
  cloud:
    stream:
      function:
        definition: topicConsumer
      bindings:
        topicConsumer-in-0:
          destination: stream-topic
          group: happyGroup
          consumer:
            batch-mode: false
          binder: retail-kafka
      binders:
        retail-kafka:
          type: kafka
