spring:
  config:
    activate:
      on-profile: local
  cloud:
    stream:
      kafka:
        binder:
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            auto.offset.reset: latest
        bindings:
          topicConsumer-in-0:
            consumer:
              start-offset: earliest
              dlq-name: topicConsumerFail
              enable-dlq: true
      bindings:
        topicConsumer-in-0:
          destination: stream-topic
          consumer:
            batch-mode: false
          group: happyEndingGroup
          binder: retail-kafka
      binders:
        retail-kafka:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: localhost:9092,localhost:9093,localhost:9094
    function:
      definition: topicConsumer

logging:
  level:
    org.springframework.web: DEBUG
    com.kakaopaysec.happyending: DEBUG
