@startuml
'https://plantuml.com/sequence-diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "연금저축펀드" #Transparent
actor Alice
boundary 모바일앱 as MOBILE
boundary "연금저축펀드 API" as PENSION
boundary "연금저축펀드 증권 API" as SECURITIES
end box

== 연금저축계좌홈 - 납입하기 ==
group 한번채우기 설정 (TODO 채우기 조건 확인 후 업데이트 예정)
    autonumber
    Alice -> MOBILE: 한번 채우기 클릭
    activate MOBILE #FFBBBB
        MOBILE -> PENSION: POST 입금가능여부 조회(정리필요. 1.연금수령개시계쫘는 입금가능X, 2. 이관신청계좌인 경우,입금가능X)
        activate MOBILE #LightSalmon
        activate PENSION #LightSalmon
            PENSION -> PENSION: <<createRequest>>
            create boundary "증권플랫폼 API" as BUFFET
            PENSION -> BUFFET ++: (NEW) 입금가능 상태조회
            return 입금가능여부
            PENSION <-- PENSION: <<createResponse>>
            return 입금가능여부
        deactivate PENSION
            alt 입금가능X
                Alice <-- MOBILE: 입금 불가 알림
            else 입금가능O
                create boundary "머니플랫폼 화면" as MONEYFE
                MOBILE -> MONEYFE: 한번채우기 화면으로 이동
                MONEYFE -> MONEYFE: 한번채우기 실행
                MOBILE <-- MONEYFE: 한번채우기 완료
            end
        deactivate MOBILE
        Alice <-- MOBILE: 한번채우기 완료
    deactivate MOBILE
end

group 자동채우기 설정
    autonumber
    Alice -> MOBILE: 자동채우기 설정 화면 진입
    activate MOBILE #FFBBBB
        MOBILE -> PENSION: POST 자동채우기 납입금액 최소/최대값 조회
        activate MOBILE #LightSalmon
        activate PENSION #LightSalmon
            PENSION -> PENSION: <<createRequest>>
            PENSION -> SECURITIES ++: (NEW) 자동채우기 납입금액 최소/최대값 조회
            return 자동채우기 납입금액 최소/최대값
            PENSION <-- PENSION: <<createResponse>>
            return 자동채우기 납입금액 최소/최대값
        deactivate PENSION
        return 자동채우기 납입금액 범위
        deactivate MOBILE
    deactivate MOBILE
    Alice -> MOBILE: 자동채우기 설정(납입금액, 주기) 입력 & 확인 클릭
    activate MOBILE #FFBBBB
        MOBILE -> PENSION: POST 자동채우기 설정
        activate MOBILE #DarkSalmon
        activate PENSION #DarkSalmon
            PENSION -> PENSION: <<createRequest>>
            PENSION -> SECURITIES ++: (NEW) 자동채우기 설정
            return 자동채우기 신청완료
            PENSION <-- PENSION: <<createResponse>>
            return 자동채우기 신청완료
        deactivate PENSION
        return 자동채우기 신청완료
        deactivate MOBILE
    deactivate MOBILE
end
@enduml
