spring:
  config:
    activate:
      on-profile: local
    import:
      - mysql.yml
      - client.yml
      - optional:vault://
  cloud:
    vault:
      uri: http://localhost:8200
      token: 00000000-0000-0000-0000-000000000000
      kv:
        backend: secret
        default-context: application

happy-ending:
  file:
    path: /Users/limjun-young/workspace/privacy/dev/test

logging:
  level:
    org.springframework.web: DEBUG
    com.kakaopaysec.happyending: DEBUG
